name: Tests 
on: 
  push:
    branches:
      - '*'
      # we don't want to run test suit when pushing to master 
      #   since it will only contain production ready code!
      - '!master'
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm ci
              
      - name: Build CSS 
        run: npm run build

      - name: Build with maven
        run: mvn clean package 

      - name: Start servers
        run: |
          cp src/main/liberty/config/server.env.example src/main/liberty/config/server.env
          mvn liberty:create liberty:install-feature liberty:deploy
          mvn liberty:start
          docker-compose up -d db
          wget https://raw.githubusercontent.com/Underflowers/Underification/master/docker-compose.yml -O docker-compose.underification.yml
          docker-compose -f docker-compose.underfication.yml up -d

      - name: Run maven tests
        run: |
          cp src/test/resources/arquillian.xml.example src/test/resources/arquillian.xml
          mvn verify

      - name: Run e2e tests
        run: |
          cd e2e
          npx codeceptjs run --override '{"helpers": {"Puppeteer": {"show": false}}}' --steps

      - name: Stop servers
        run: |
          mvn liberty:stop
          docker-compose down
          docker-compose -f docker-compose.underification.yml down
